name: Check-Consistency
on:
  pull_request:
    branches:
    - master
jobs:
  run-checks:
    name: run-checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: install-nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}
      - run: npm install
      - run: npm run check